#!/bin/sh
# PNGs do heroi antigo + code4.js (o clone da fase 2 foi abandonado).

rm -f "Attack-1.png"
rm -f "Attack-2.png"
rm -f "Attack-3.png"
rm -f "Attack-4.png"
rm -f "Attack-5.png"
rm -f "Attack-6.png"
rm -f "HeroAttackHitbox-1.png"
rm -f "Hit-1.png"
rm -f "Idle-1.png"
rm -f "Idle-2.png"
rm -f "Idle-3.png"
rm -f "Idle-4.png"
rm -f "Jump-1.png"
rm -f "Jump-2.png"
rm -f "Jump-3.png"
rm -f "Jump-4.png"
rm -f "Run-1.png"
rm -f "Run-2.png"
rm -f "Run-3.png"
rm -f "Run-4.png"
rm -f "Run-5.png"
rm -f "Run-6.png"
rm -f "code4.js"

echo "arquivos obsoletos removidos."
